"""Export held-out errors separately from predictions from the latest configured year."""

from pathlib import Path

import joblib
import numpy as np

from osaka_geo_ai.config import artifact, directory
from osaka_geo_ai.data.loader import read_geo
from osaka_geo_ai.io import read_json, sha256, write_json


def validate_prediction_contract(config):
    manifest = read_json(artifact(config, "predictions/prediction_metadata.json"))
    for item in manifest["inputs"] + manifest["outputs"]:
        path = Path(config["_root"]) / item["path"]
        if not path.exists() or sha256(path) != item["sha256"]:
            raise ValueError(
                f"Prediction artifact contract changed: {path}; rerun train/predict as appropriate"
            )
    return manifest


def predict(config):
    feature_path = directory(config, "processed") / "features.parquet"
    frame = read_geo(feature_path)
    output = artifact(config, "predictions")
    output.mkdir(parents=True, exist_ok=True)
    for filename, role in [("model.joblib", "test"), ("forecast_model.joblib", "forecast")]:
        # Only load artifacts generated by this project; pickle/joblib is not an untrusted input format.
        bundle = joblib.load(artifact(config, f"models/{filename}"))
        if bundle["features_sha256"] != sha256(feature_path):
            raise ValueError("Features changed since training; rerun train_model.py")
        if role == "test":
            rows = frame[
                frame.target_year.eq(config["model"]["test_target_year"])
                & frame[bundle["target"]].notna()
            ].copy()
        else:
            rows = frame[frame.year.eq(frame.year.max())].copy()
        if rows.empty or bundle["fit_max_target_year"] > rows.year.min():
            raise ValueError(f"Empty prediction input or future training labels for {role}")
        rows["prediction"] = bundle["estimator"].predict(rows[bundle["features"]])
        if not np.isfinite(rows.prediction).all():
            raise ValueError("Nonfinite model predictions")
        rows["actual"] = rows[bundle["target"]] if role == "test" else np.nan
        rows["residual"] = rows.actual - rows.prediction
        rows["predicted_land_price"] = rows.land_price * (1 + rows.prediction)
        rows["prediction_role"] = role
        rows["model_name"] = bundle["name"]
        rows["fit_max_target_year"] = bundle["fit_max_target_year"]
        cols = [
            "row_id",
            "site_id",
            "municipality_code",
            "municipality_name",
            "year",
            "target_year",
            "longitude",
            "latitude",
            "land_price",
            "prediction",
            "actual",
            "residual",
            "predicted_land_price",
            "prediction_role",
            "model_name",
            "fit_max_target_year",
            "geometry",
        ]
        rows[cols].to_parquet(
            output / ("predictions.parquet" if role == "test" else "forecast.parquet"), index=False
        )
    root = Path(config["_root"])
    inputs = [
        feature_path,
        artifact(config, "models/model.joblib"),
        artifact(config, "models/forecast_model.joblib"),
        artifact(config, "metrics/metrics.json"),
    ]
    outputs = [output / "predictions.parquet", output / "forecast.parquet"]
    write_json(
        output / "prediction_metadata.json",
        {
            "schema_version": "1.0",
            "inputs": [{"path": str(p.relative_to(root)), "sha256": sha256(p)} for p in inputs],
            "outputs": [{"path": str(p.relative_to(root)), "sha256": sha256(p)} for p in outputs],
        },
    )
    return output / "predictions.parquet"
